---

- name: get binary
  get_url:
    url: "{{ prometheus_redis_exporter_distrib }}"
    dest: "/var/cache/apt/archives/redis_exporter-v{{ prometheus_redis_exporter_version }}.linux-amd64.tar.gz"
  register: redis_exporter_downloaded

- name: unarchive binary
  unarchive:
    src: "/var/cache/apt/archives/redis_exporter-v{{ prometheus_redis_exporter_version }}.linux-amd64.tar.gz"
    dest: /var/cache/apt/archives
    remote_src: yes
  when: redis_exporter_downloaded.changed

- name: install binary
  copy:
    src: "/var/cache/apt/archives/redis_exporter"
    dest: /usr/local/bin/redis_exporter
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: 0755
  register: redis_exporter_installed

- name: write systemd configs
  template:
    src: "{{ ansible_service_mgr }}/redis_exporter.service.j2"
    dest: "/etc/systemd/system/redis_exporter.service"
  when: ansible_service_mgr == 'systemd'
  register: redis_exporter_systemd_updated
  notify: [reload systemd]

- meta: flush_handlers
  when: redis_exporter_systemd_updated.changed

- name: restart redis_exporter service (systemd)
  service:
    name: redis_exporter
    state: restarted
    enabled: yes
  when: redis_exporter_installed.changed or redis_exporter_systemd_updated.changed
